name: solar system workflows

on: 
    push:
        branches:
            - 'main'
            - 'feature/*'
jobs:
    unit-testing:
        name: unit testing
        runs-on: ubuntu-latest

        steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: setup nodejs version 18
              uses: actions/setup-node@v3

              with:
                node-version: 18

            - name: install depend.
              run: npm install

            - name: unit test
              run: npm test
